#  Copyright 2017 Google Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 01:42
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('bathrooms', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=2)),
                ('bedrooms', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=3)),
                ('car_spaces', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=1)),
                ('description', models.TextField()),
                ('point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, unique=True)),
                ('property_type', models.IntegerField(choices=[(1, b'House'), (2, b'Townhouse'), (3, b'Apartment'), (4, b'Studio')], default=1)),
                ('nearest_school', models.CharField(max_length=1000, null=True)),
                ('nearest_school_distance', models.FloatField(null=True)),
                ('nearest_train_station', models.CharField(max_length=1000, null=True)),
                ('nearest_train_station_distance', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
